var searchData=
[
  ['unbound_0',['Unbound',['../classiceberg_1_1Unbound.html',1,'iceberg']]],
  ['unbound_3c_20boundreference_20_3e_1',['Unbound&lt; BoundReference &gt;',['../classiceberg_1_1Unbound.html',1,'iceberg']]],
  ['unbound_3c_20class_20boundtransform_20_3e_2',['Unbound&lt; class BoundTransform &gt;',['../classiceberg_1_1Unbound.html',1,'iceberg']]],
  ['unbound_3c_20expression_20_3e_3',['Unbound&lt; Expression &gt;',['../classiceberg_1_1Unbound.html',1,'iceberg']]],
  ['unboundaggregate_4',['UnboundAggregate',['../classiceberg_1_1UnboundAggregate.html',1,'iceberg']]],
  ['unboundaggregateimpl_5',['UnboundAggregateImpl',['../classiceberg_1_1UnboundAggregateImpl.html',1,'iceberg']]],
  ['unboundpredicate_6',['UnboundPredicate',['../classiceberg_1_1UnboundPredicate.html',1,'iceberg']]],
  ['unboundpredicateimpl_7',['UnboundPredicateImpl',['../classiceberg_1_1UnboundPredicateImpl.html',1,'iceberg']]],
  ['unboundterm_8',['UnboundTerm',['../classiceberg_1_1UnboundTerm.html',1,'iceberg']]],
  ['unboundterm_3c_20boundreference_20_3e_9',['UnboundTerm&lt; BoundReference &gt;',['../classiceberg_1_1UnboundTerm.html',1,'iceberg']]],
  ['unboundterm_3c_20class_20boundtransform_20_3e_10',['UnboundTerm&lt; class BoundTransform &gt;',['../classiceberg_1_1UnboundTerm.html',1,'iceberg']]],
  ['unboundtransform_11',['UnboundTransform',['../classiceberg_1_1UnboundTransform.html',1,'iceberg']]],
  ['uniqueconstraintsrequest_12',['UniqueConstraintsRequest',['../classApache_1_1Hadoop_1_1Hive_1_1UniqueConstraintsRequest.html',1,'Apache::Hadoop::Hive']]],
  ['uniqueconstraintsresponse_13',['UniqueConstraintsResponse',['../classApache_1_1Hadoop_1_1Hive_1_1UniqueConstraintsResponse.html',1,'Apache::Hadoop::Hive']]],
  ['unknowndbexception_14',['UnknownDBException',['../classApache_1_1Hadoop_1_1Hive_1_1UnknownDBException.html',1,'Apache::Hadoop::Hive']]],
  ['unknownpartitionexception_15',['UnknownPartitionException',['../classApache_1_1Hadoop_1_1Hive_1_1UnknownPartitionException.html',1,'Apache::Hadoop::Hive']]],
  ['unknowntableexception_16',['UnknownTableException',['../classApache_1_1Hadoop_1_1Hive_1_1UnknownTableException.html',1,'Apache::Hadoop::Hive']]],
  ['unknowntype_17',['UnknownType',['../classiceberg_1_1UnknownType.html',1,'iceberg']]],
  ['unlockrequest_18',['UnlockRequest',['../classApache_1_1Hadoop_1_1Hive_1_1UnlockRequest.html',1,'Apache::Hadoop::Hive']]],
  ['updatelocation_19',['UpdateLocation',['../classiceberg_1_1UpdateLocation.html',1,'iceberg']]],
  ['updatelocationtest_20',['UpdateLocationTest',['../classiceberg_1_1UpdateLocationTest.html',1,'iceberg']]],
  ['updatemappingtest_21',['UpdateMappingTest',['../classiceberg_1_1UpdateMappingTest.html',1,'iceberg']]],
  ['updatenamespacepropertiesrequest_22',['UpdateNamespacePropertiesRequest',['../structiceberg_1_1rest_1_1UpdateNamespacePropertiesRequest.html',1,'iceberg::rest']]],
  ['updatenamespacepropertiesresponse_23',['UpdateNamespacePropertiesResponse',['../structiceberg_1_1rest_1_1UpdateNamespacePropertiesResponse.html',1,'iceberg::rest']]],
  ['updatepartitionspec_24',['UpdatePartitionSpec',['../classiceberg_1_1UpdatePartitionSpec.html',1,'iceberg']]],
  ['updatepartitionspectest_25',['UpdatePartitionSpecTest',['../classiceberg_1_1UpdatePartitionSpecTest.html',1,'iceberg']]],
  ['updatepartitionstatistics_26',['UpdatePartitionStatistics',['../classiceberg_1_1UpdatePartitionStatistics.html',1,'iceberg']]],
  ['updatepartitionstatisticstest_27',['UpdatePartitionStatisticsTest',['../classiceberg_1_1UpdatePartitionStatisticsTest.html',1,'iceberg']]],
  ['updateproperties_28',['UpdateProperties',['../classiceberg_1_1UpdateProperties.html',1,'iceberg']]],
  ['updatepropertiestest_29',['UpdatePropertiesTest',['../classiceberg_1_1UpdatePropertiesTest.html',1,'iceberg']]],
  ['updateschema_30',['UpdateSchema',['../classiceberg_1_1UpdateSchema.html',1,'iceberg']]],
  ['updateschematest_31',['UpdateSchemaTest',['../classiceberg_1_1UpdateSchemaTest.html',1,'iceberg']]],
  ['updatesnapshotreference_32',['UpdateSnapshotReference',['../classiceberg_1_1UpdateSnapshotReference.html',1,'iceberg']]],
  ['updatesortorder_33',['UpdateSortOrder',['../classiceberg_1_1UpdateSortOrder.html',1,'iceberg']]],
  ['updatesortordertest_34',['UpdateSortOrderTest',['../classiceberg_1_1UpdateSortOrderTest.html',1,'iceberg']]],
  ['updatestatistics_35',['UpdateStatistics',['../classiceberg_1_1UpdateStatistics.html',1,'iceberg']]],
  ['updatestatisticsretrytest_36',['UpdateStatisticsRetryTest',['../classiceberg_1_1UpdateStatisticsRetryTest.html',1,'iceberg']]],
  ['updatestatisticstest_37',['UpdateStatisticsTest',['../classiceberg_1_1UpdateStatisticsTest.html',1,'iceberg']]],
  ['updatetestbase_38',['UpdateTestBase',['../classiceberg_1_1UpdateTestBase.html',1,'iceberg']]],
  ['updatetransactionalstatsrequest_39',['UpdateTransactionalStatsRequest',['../classApache_1_1Hadoop_1_1Hive_1_1UpdateTransactionalStatsRequest.html',1,'Apache::Hadoop::Hive']]],
  ['upgradeformatversion_40',['UpgradeFormatVersion',['../classiceberg_1_1table_1_1UpgradeFormatVersion.html',1,'iceberg::table']]],
  ['urlencoder_41',['UrlEncoder',['../classiceberg_1_1UrlEncoder.html',1,'iceberg']]],
  ['uuid_42',['Uuid',['../classiceberg_1_1Uuid.html',1,'iceberg']]],
  ['uuidtype_43',['UuidType',['../classiceberg_1_1UuidType.html',1,'iceberg']]]
];
