# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: "Release Docs"

on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          make install-deps

      - name: Build API documentation with Doxygen
        run: make build-api-docs

      - name: Build docs
        run: |
            make build-docs
            mkdir -p /tmp/site
            cp -r ./mkdocs/site/* /tmp/site/

      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git checkout --orphan gh-pages-tmp
          git rm --quiet -rf .
          cp -r /tmp/site/* .
          echo "cpp.iceberg.apache.org" > CNAME
          git add --all
          git commit -m "Publish docs from commit ${{ github.sha }}"
          git push -f origin gh-pages-tmp:gh-pages
